version: '3.8'
services: 
  mysqldb:
    image: mysql:8.0
    container_name: mysqldbcontanier
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  phphmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    depends_on:
      - mysqldb
    container_name: phpmyadmincontainer 
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
    volumes:
      - /sessions

  phpapp:
    build: .
    image: ecommercephpapp:v1.0
    container_name: vuln_ecommerce 
    restart: unless-stopped
    depends_on:
      - mysqldb
    ports:
      - "8000:80"
    stdin_open: true
    tty: true
    volumes:
      - ./app:/var/www/html
  
volumes:
  mysql-data:
  



